### ISSUE TITLE
Is it broken or something?

### ISSUE THREAD

**Issue by DracoNight9924** [smell-of-curry/rubedo#16]
I use Rubeo and it is such a great anti hack. I've blocked like over 100 players but every time I leave, and no players are on my realm. ALL of my settings reset. can that be fixed or is that only because I have over 10,000 mods on my realm? (I'm exaggerating I only have like 12)

**Comment by joshuaworld** [comment]
I've had the exact same problem, I have around 6 mods on my realm and when no players are on for about a day, all my settings reset and I have to re-configure my settings and set my role to Admin so I don't get false-flagged.

**Comment by DracoNight9924** [comment]
yeah I tried going into the file settings but didnt work. there are however multiple file areas that contain the data for the settings. not exactly easy. That was the main suggestion for solving but it just dont work.
